### ISSUE TITLE
How to detect Vapoursynth API version?

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [YaLTeR/vapoursynth-rs#11]
In README I saw this table:

```
vapoursynth-api-31 for VapourSynth API 3.1 (R26)
vapoursynth-api-32 for VapourSynth API 3.2 (R27)
vapoursynth-api-33 for VapourSynth API 3.3 (R30)
vapoursynth-api-34 for VapourSynth API 3.4 (R30)
vapoursynth-api-35 for VapourSynth API 3.5 (R38)
vapoursynth-api-36 for VapourSynth API 3.6 (R47)
```

But all Vapoursynth versions are labeled in Rxx (e.g, R52) format, not in `x.x` format. How can I map them?

**Comment by YaLTeR** [comment]
It says in the end of every line:

> ```
> vapoursynth-api-31 for VapourSynth API 3.1 (R26)
> vapoursynth-api-32 for VapourSynth API 3.2 (R27)
> vapoursynth-api-33 for VapourSynth API 3.3 (R30)
> vapoursynth-api-34 for VapourSynth API 3.4 (R30)
> vapoursynth-api-35 for VapourSynth API 3.5 (R38)
> vapoursynth-api-36 for VapourSynth API 3.6 (R47)
> ```

**Comment by Doko-Demo-Doa** [comment]
Sorry if I wasn't clear. How can I detect VapourSynth API version? When using:

```bash
vspipe -v
```
with VapourSynth R52, it prints:

```
VapourSynth Video Processing Library
Copyright (c) 2012-2020 Fredrik Mellbin
Core R52
API R3.6
Options: -
```

so the API version here is 3.6, right? Does that mean VapourSynth R47 and R52 have the same API version?

**Comment by YaLTeR** [comment]
Yeah, the crate feature you enable indicates the lowest vapoursynth API version you want to support.

**Comment by YaLTeR** [comment]
Did I answer your question?

**Comment by Doko-Demo-Doa** [comment]
Yes, thank you very much, the only thing I need to know is whether VapourSynth R47 and R52 have the same API version or different. And the answer is "same".

Actually there is a problem with `vapoursynth-rs` with VapourSynth R52. Also `failure` crate is deprecated. But they are different issues.

**Comment by YaLTeR** [comment]
> Actually there is a problem with vapoursynth-rs with VapourSynth R52.

Could you make a separate issue about the problem?

> Also failure crate is deprecated.

Yeah, I haven't worked on the crate in a while.
