### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by redzic** [YaLTeR/vapoursynth-rs#20]
Hi, the git version of av1an is currently depending on a git version of vapoursynth-rs (because of the removal of the `failure` crate), so it would be nice if there was a new release that contains the new changes so we don't have to depend on a git version of this crate anymore, especially since releases to crates.io cannot contain git dependencies.

Thanks!

**Comment by YaLTeR** [comment]
Hey, I can publish a release. Are there any other changes that need to be made before that?

**Comment by redzic** [comment]
> Are there any other changes that need to be made before that?

I don't think so, it should in theory be good to go in its current state. Thanks!

**Comment by YaLTeR** [comment]
Published v0.4. Hopefully didn't break anything :)

**Comment by redzic** [comment]
Thanks so much!
