### ISSUE TITLE
vapoursynth-sys: Add a `default_library_dir` for macOS

### ISSUE THREAD

**Issue by FreezyLemon** [YaLTeR/vapoursynth-rs#23]
See https://github.com/master-of-zen/Av1an/issues/815.

For most mac users installing vapoursynth via homebrew, it should be helpful to add `/opt/homebrew/lib` to the `rustc-link-search` similar to how it's currently done for Windows.

**Comment by YaLTeR** [comment]
Do you mind submitting a PR? I don't have a macOS system to test this.

**Comment by FreezyLemon** [comment]
I wouldn't mind, but I don't have a mac system either. I see you have a few CI workflows set up, I'll take a look to see if I can add one to test this behavior

**Comment by quietvoid** [comment]
I can test on macOS system if you can clarify what needs to work.
Is it just about building this crate?

**Comment by FreezyLemon** [comment]
The gist of it is that people who install VS via homebrew should be able to build the crate without needing to manually change the PKG_CONFIG_PATH, LIBRARY_PATH or other environment variables.

The easiest way to accomplish this is probably the one I described above with a println! for rustc-link-search

**Comment by quietvoid** [comment]
I'm unable to reproduce the issue on my system, macOS with M2.
Everything builds and seems to work fine out of the box.

```console
otool -L vspipe
vspipe:
	/opt/homebrew/opt/vapoursynth/lib/libvapoursynth.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/homebrew/opt/vapoursynth/lib/libvapoursynth-script.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.100.2)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
```

Everything is symlinked, FYI:
```bash
ls -la /opt/homebrew/lib | rg -i vapoursynth
libvapoursynth-script.0.dylib -> ../Cellar/vapoursynth/69/lib/libvapoursynth-script.0.dylib
libvapoursynth-script.a -> ../Cellar/vapoursynth/69/lib/libvapoursynth-script.a
libvapoursynth-script.dylib -> ../Cellar/vapoursynth/69/lib/libvapoursynth-script.dylib
libvapoursynth.a -> ../Cellar/vapoursynth/69/lib/libvapoursynth.a
libvapoursynth.dylib -> ../Cellar/vapoursynth/69/lib/libvapoursynth.dylib

ls -la /opt/homebrew/opt | rg -i vapoursynth
vapoursynth -> ../Cellar/vapoursynth/69
```

It looks like the user is missing the homebrew prefix in `LIBRARY_PATH`.
I have it in my `.zshrc` so everything works fine, for example:
```bash
export CPATH="$HOMEBREW_PREFIX/include:$CPATH"
export LIBRARY_PATH="$HOMEBREW_PREFIX/lib:$LIBRARY_PATH"
```

**Comment by FreezyLemon** [comment]
>  Everything builds and seems to work fine out of the box.
> ...
> It looks like the user is missing the homebrew prefix in LIBRARY_PATH.

This makes sense, one user reported fixing the problem by setting `LIBRARY_PATH` manually in that issue. It seems like installing homebrew won't include the prefix in the LIBRARY_PATH out of the box though.

I guess the question is whether this should be up to the crate user or not. I think it would make sense to discover the homebrew directories automatically because it is simple to do.
