### ISSUE TITLE
vapoursynth-sys 0.4.1 release

### ISSUE THREAD

**Issue by FreezyLemon** [YaLTeR/vapoursynth-rs#26]
Unless something else is planned, it would be nice to have the change from #25 in a crates.io release so we can update it in downstream projects.

E.g. https://github.com/master-of-zen/Av1an/issues/815 and https://github.com/rust-av/ssimulacra2_bin/issues/33

**Comment by YaLTeR** [comment]
Is there anything else needed or can I publish it as is?

**Comment by FreezyLemon** [comment]
Nothing that I'm aware of. Unless #21 is something easy to do? It's also about building the -sys crate, but it's not something I would know how to implement off the top of my head.

**Comment by YaLTeR** [comment]
Published, please test.
