### ISSUE TITLE
Memory leak by av_malloc

### ISSUE THREAD

**Issue by SuspiciousDuck** [YaLTeR/vapoursynth-rs#28]
I've tried using [vapoursynth-ssimulacra2](https://github.com/dnjulek/vapoursynth-ssimulacra2), [vapoursynth-zip](https://github.com/dnjulek/vapoursynth-zip), and [ssimulacra2](https://github.com/rust-av/ssimulacra2_bin) to calculate quality scores for videos. All 3 suffer from the same, several gigabyte memory leak in av_malloc. All 3 use vapoursynth-rs in order to retrieve video frames. It happens when the Node is retrieved; av_malloc is called but av_free is never called, which leaks memory. The reason you can't notice this when running the original ssimulacra2_bin, is because that only runs once.
![image](https://github.com/user-attachments/assets/19f1e652-711c-464e-af3c-875c7b3a3e5f)

**Comment by YaLTeR** [comment]
Hmm, to be honest I no longer remember what the memory management is supposed to look like there.

**Comment by quietvoid** [comment]
`av_malloc` is a ffmpeg function and it's not directly used by any of the Rust libraries.
Most likely it's caused by the decoding process.

**Comment by SuspiciousDuck** [comment]
Yes, I think it may have been through the decoding process. ssimulacra2_rs uses LSMASHSource for decoding, which I believe uses ffmpeg. However, there surely must be a way to trigger av_free.

**Comment by FreezyLemon** [comment]
> All 3 suffer from the same

Those three libraries use two different libraries for interfacing with VS (one Rust, one Zig), it feels a bit unlikely that both have the exact same memory leak. This might be a bug in the underlying plugin LSMASHSOURCE and not the Zig/Rust applications.

> However, there surely must be a way to trigger av_free.

That *should* be handled by VS and/or the VS plugin when the Node is freed... Calling `av_free` from Rust/Zig when the memory was allocated somewhere else is just asking for trouble.

The `Drop` code for the VSNodeRef looks correct at first glance:

https://github.com/YaLTeR/vapoursynth-rs/blob/b9dee6d2a12c089885aa2d723c57685fa9885e48/vapoursynth/src/node/mod.rs#L57-L64

> The reason you can't notice this when running the original ssimulacra2_bin, is because that only runs once.

Do you have example code (modified ssimulacra2_bin?) where this can be reproduced?

**Comment by SuspiciousDuck** [comment]
All 3 libraries had the same problem because I had used LSMASHSource for retrieving the node. The code I used to reproduce this for ssimulacra2_rs is a modified version of video.rs in ssimulacra2_bin, which can be found [here](https://github.com/SuspiciousDuck/grav1an/blob/main/src/ssimulacra2.rs). You can call it with `get_ssimu2(reference path, distorted path, # of frames skipped or 1, "full", "bt709", "bt709", "bt709")`. You should be able to see the memory not go down even after the first call finishes.

**Comment by SuspiciousDuck** [comment]
Nevermind, it looks like the memory leak goes away when I used the git version of BestSource (I was using the official Archlinux package, which was outdated).

**Comment by YaLTeR** [comment]
Thanks for looking into this.
